# Graph randomization

 In this notebook calcium events data (further - spikes) is randomized with 2 different methods:  
 1. Spike shuffle  
 2. Dynamic shift spikes  

In [1]:
import numpy as np
import graph_randomization as gr


Spikes is an array with shape $N \times T$, where $N$ - number of cells, $T$ - number of frames in video. For demo we used prepared array with shape $10 \times 100$

In [2]:
path_spikes = r"D:\practice_v2\scripts\triple_patterns\data\spikes.npy"
spikes = np.load(path_spikes, allow_pickle=True)
spikes.shape

(10, 100)

To check the accuracy (?) of randomization, some calculations before and after randomizations are shown below:  
1. Number of spikes in the whole array  
2. Indices of the first 5 spikes in one cell.

In [3]:
print(f"Number of spikes before randomization = {np.count_nonzero(spikes)}")
print(f"Indices of the first 5 spikes before randomization =\n {np.argwhere(spikes[0, :])[:5]}")

Number of spikes before randomization = 100
Indices of the first 5 spikes before randomization =
 [[ 4]
 [19]
 [48]
 [55]
 [60]]


### 1. Spikes shuffle
It is the method of randomization, where spikes are shuffled along time axis.

In [4]:
shuffled_spikes = gr.shuffle_along_axis(spikes, axis=0, random_state=0)
print(f"Number of spikes after shuffle randomization = {np.count_nonzero(shuffled_spikes)}")
print(f"Indices of the first 5 spikes after shuffle randomization =\n {np.argwhere(shuffled_spikes[0, :])[:5]}")

Number of spikes after shuffle randomization = 100
Indices of the first 5 spikes after shuffle randomization =
 [[ 5]
 [ 7]
 [35]
 [50]
 [60]]


### 2. Dynamic shift

It is the method of randomization, where spikes are shifted by random number of frames for each cell independently.

In [5]:
shifted_spikes, _ = gr.calc_randomized_shift_spikes(spikes, axis=0, random_state=0)
print(f"Number of spikes after shift randomization = {np.count_nonzero(shifted_spikes)}")
print(f"Indices of the first 5 spikes after shift randomization =\n {np.argwhere(shifted_spikes[0, :])[:5]}")

Number of spikes after shift randomization = 100
Indices of the first 5 spikes after shift randomization =
 [[ 8]
 [42]
 [53]
 [61]
 [68]]
